version: "3"
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data{1...2} --console-address ":9001"
    volumes:
      - ./config.env:/etc/config.env
      - /mnt/disk1:/data1
      - /mnt/disk2:/data2