version: "3"
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=512m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs
    ports:
      - 8081:8081
      - 8443:8443
      - 5000-5001:5000
    volumes:
      - ./ssl:/opt/sonatype/nexus/etc/ssl
      - ./jetty-https.xml:/opt/sonatype/nexus/etc/jetty/jetty-https.xml
      - ./nexus.properties:/opt/sonatype/nexus/etc/nexus.properties
      - nexus-data:/nexus-data
volumes:
  nexus-data:
    external: true